"""Shared type definitions, Pydantic models, and enumerations for OpsBrain."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class Provider(StrEnum):
    """Supported LLM provider identifiers."""

    OPENAI = "openai"
    GEMINI = "gemini"
    ANTHROPIC = "anthropic"
    OLLAMA = "ollama"
    LITELLM = "litellm"


class AgentRole(StrEnum):
    """Roles that an agent can assume within a pipeline."""

    MONITOR = "monitor"
    RCA = "rca"
    SOLVER = "solver"
    COORDINATOR = "coordinator"
    EVALUATOR = "evaluator"


class Severity(StrEnum):
    """Severity levels for alerts and incidents."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class IncidentStatus(StrEnum):
    """State machine states for incident lifecycle."""

    DETECTED = "detected"
    ANALYZING = "analyzing"
    DIAGNOSED = "diagnosed"
    RESOLVING = "resolving"
    RESOLVED = "resolved"
    CLOSED = "closed"


# ---------------------------------------------------------------------------
# LLM Request / Response
# ---------------------------------------------------------------------------

class ToolDefinition(BaseModel):
    """Definition of a tool that an LLM can call."""

    name: str
    description: str
    parameters: dict[str, Any] = Field(default_factory=dict)


class ToolCall(BaseModel):
    """A tool invocation returned by the LLM."""

    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    name: str
    arguments: dict[str, Any] = Field(default_factory=dict)


class Message(BaseModel):
    """A single message in a conversation."""

    role: str  # "system" | "user" | "assistant" | "tool"
    content: str
    tool_calls: list[ToolCall] | None = None
    tool_call_id: str | None = None
    name: str | None = None


class LLMRequest(BaseModel):
    """Unified request object sent to any LLM provider."""

    messages: list[Message]
    model: str | None = None
    temperature: float = 0.7
    max_tokens: int | None = None
    tools: list[ToolDefinition] | None = None
    response_format: dict[str, Any] | None = None
    stop: list[str] | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class UsageStats(BaseModel):
    """Token usage and cost information for a single LLM call."""

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    cost_usd: float | None = None
    latency_ms: float | None = None


class LLMResponse(BaseModel):
    """Unified response object returned from any LLM provider."""

    content: str = ""
    tool_calls: list[ToolCall] = Field(default_factory=list)
    model: str = ""
    provider: Provider = Provider.LITELLM
    usage: UsageStats = Field(default_factory=UsageStats)
    raw: dict[str, Any] = Field(default_factory=dict)
    finish_reason: str | None = None


# ---------------------------------------------------------------------------
# Operational Data Types
# ---------------------------------------------------------------------------

class Metric(BaseModel):
    """A single metric data point."""

    name: str
    value: float
    unit: str = ""
    source: str = ""
    labels: dict[str, str] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class LogEntry(BaseModel):
    """A single log entry from an operational system."""

    message: str
    level: str = "info"
    source: str = ""
    labels: dict[str, str] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class Alert(BaseModel):
    """An alert generated by the Monitor Agent."""

    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:16])
    title: str
    description: str
    severity: Severity = Severity.MEDIUM
    source: str = ""
    affected_systems: list[str] = Field(default_factory=list)
    evidence: list[str] = Field(default_factory=list)
    metrics: list[Metric] = Field(default_factory=list)
    logs: list[LogEntry] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


# ---------------------------------------------------------------------------
# Agent Communication Types
# ---------------------------------------------------------------------------

class AgentMessage(BaseModel):
    """Message passed between agents via the event bus."""

    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:16])
    sender: AgentRole
    recipient: AgentRole | None = None  # None = broadcast
    content: str
    data: dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class RCAReport(BaseModel):
    """Root cause analysis report produced by the RCA Agent."""

    incident_id: str = ""
    root_cause: str
    evidence_chain: list[str] = Field(default_factory=list)
    affected_systems: list[str] = Field(default_factory=list)
    confidence: float = 0.0  # 0.0 – 1.0
    contributing_factors: list[str] = Field(default_factory=list)
    timeline: list[str] = Field(default_factory=list)


class Solution(BaseModel):
    """A solution proposed by the Solver Agent."""

    title: str
    steps: list[str] = Field(default_factory=list)
    risk_level: Severity = Severity.LOW
    estimated_time_minutes: int | None = None
    prerequisites: list[str] = Field(default_factory=list)
    rollback_plan: str = ""
    confidence: float = 0.0


class ActionItem(BaseModel):
    """A single action item assigned to a team or individual."""

    description: str
    assignee: str = ""
    team: str = ""
    priority: Severity = Severity.MEDIUM
    due_by: str = ""
    status: str = "pending"


class ResolutionPlan(BaseModel):
    """Cross-team resolution plan produced by the Coordinator Agent."""

    incident_id: str = ""
    summary: str
    action_items: list[ActionItem] = Field(default_factory=list)
    stakeholders: list[str] = Field(default_factory=list)
    communication_draft: str = ""
    escalation_path: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Incident (aggregate)
# ---------------------------------------------------------------------------

class Incident(BaseModel):
    """Full incident record tracking the lifecycle from detection to resolution."""

    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:16])
    title: str = ""
    description: str = ""
    source: str = ""
    status: IncidentStatus = IncidentStatus.DETECTED
    severity: Severity = Severity.MEDIUM
    alerts: list[Alert] = Field(default_factory=list)
    rca_report: RCAReport | None = None
    solutions: list[Solution] = Field(default_factory=list)
    resolution_plan: ResolutionPlan | None = None
    audit_log: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    resolved_at: datetime | None = None
